name: Secrets workflow SECRET_API_KEY

on:
  pull_request:
    branches: [ "main" ]

env:
  API_CSPROJ_PATH: "src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj"
jobs:
  secrets:
    name: Secrets Demo  SECRET_API_KEY  
    runs-on: ubuntu-latest
 
    steps:
      - name: echo envariments variable
        run: echo  "The value of ${{secrets.SECRET_API_KEY}} is $API_CSPROJ_PATH"
 
        # github settings->secrets and variables->actions->Repository secrets