name: "Step-Deploy"

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true      
jobs:
  deploy:
    name: Deploy {{ inputs.env}}
    runs-on: ubuntu-latest
    environment: ${{ inputs.env}}

    steps:
    # Download artifacts to the path 'artifacts'
    - uses: actions/download-artifact@v4
      with:
        name: dometrain-artifact
        path: artifacts/

    - name: Azure Login
      uses: azure/login@v2
      with:
        # All the keys are randomly generated for the demo (don't try to hack :-) )
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: app-leonid-github-action-leonidko-${{ inputs.env}}
        package: artifacts/
